### ISSUE TITLE
You should include the LICENSE file

### ISSUE THREAD

**Issue by jmfgdev** [JadedCtrl/stic#1]
I think it is recommended to put a LICENSE file in your directory that is under a license, also it will make github recognize it and show it's fancy emblem 👍

**Comment by JadedCtrl** [comment]
This repo's dead-- I'm never planning on making a commit on it again.
I wondered why shell cli input was so terrible, then wrote this to make it better...
... without realizing getopts(1) already existed, jajaja. 
So this was a waste of time. :P
